### ISSUE TITLE
is buggy

### ISSUE THREAD

**Issue by TopazTK** [SandeMC/Kingdom-Hearts-Launchers#1]
I haz bug plz fix :(

**Comment by SandeMC** [comment]
![image](https://github.com/SandeMC/Kingdom-Hearts-Launchers/assets/70141395/bafb6f23-c1a7-4512-a481-b9257c1ad1da)

**Comment by TopazTK** [comment]
bug not fix plz fix :(

**Comment by Abelatox** [comment]
I had the same bug plz fix asap :(

**Comment by TopazTK** [comment]
But you no fix my bug? D:

**Comment by Abelatox** [comment]
you fix my bug pls

**Comment by TopazTK** [comment]
fix bug!
