### ISSUE TITLE
KH Re:Coded Melon Mix not launching

### ISSUE THREAD

**Issue by CodedRubyChan** [SandeMC/Kingdom-Hearts-Launchers#4]
I configured the launcher to launch Melon Mix instead of the movies.
I downloaded the newest Melon Mix from the Github Actions Tab of the Melon Mix Repo. 
(the newest Versions even have batch files for launching 358 Days (days.nds) or ReCoded (recoded.nds))
it only launches Days and not Re:Coded

**Comment by SandeMC** [comment]
I'm aware, the code snippet for that is currently empty - wait until melon mix supports re:coded

**Comment by SandeMC** [comment]
fixed in v1.3
