### ISSUE TITLE
cant return to title screen with this launcher

### ISSUE THREAD

**Issue by mer2329** [SandeMC/Kingdom-Hearts-Launchers#6]
as the title says you cant return to title screen with this launcher. only KH1 FM tested. 
somtimes it strait up crashes, or it eternally is loading. i primarally play with special k, as it that helps with the perodic crashes (specificly the playtime crash of 1 -3 hours of play) in the game. but with or without special k this launcher breaks returning to title screen.

to reproduce
1) launch KH1 final mix through the simple launcher. note: skip copyright screen dosent matter. it crashes weather thats enabled or disabled
2) get to the title screen and load any game save. location of the save dosent matter.
3) use the save point to try and return to the title screen.
4) the game will be stuck on the spinning heart loading screen.

expected behavior
the game returns you to the title screen with some copyright notices before. 

my specs
mobo: MSI PRO B650-P WIFI
CPU: AMD Ryzen 5 8500G
GPU: GIGABYTE GeForce RTX 4070 Ti SUPER WINDFORCE OC 16G (GV-N407TSWF3OC-16GD)
memory: 2x16 teamgroup DDR5-5200
OS: Windows 10 pro 22h2
full specs in screenshot (note: the memory clock in the screenshot is wrong. i have expo enabled and my ram is running at its intended 5200 mhz)
![image](https://github.com/user-attachments/assets/fb109462-d946-4c71-bc3a-64e531b48c44)

**Comment by SandeMC** [comment]
can't know what's the cause personally
if somebody else figures it out let me know

**Comment by mer2329** [comment]
sorry for the delay i was hospitalised.
ok tested on KH1 with the "return or original launcher" and it still gets stuck on loading.
KH re:com works though

**Comment by SandeMC** [comment]
i have no clue then

**Comment by mer2329** [comment]
KH2 return to title works.

**Comment by TopazTK** [comment]
All "Return To Title" options, apart from KH1, are genuine and will work with this launcher.
KH1 straight up crashes the game when returning to title, and reboots using the launcher, hence it won't work.
