### ISSUE TITLE
Windows Error When Downloading or Launching This Launcher

### ISSUE THREAD

**Issue by thevelcrosasquatch** [SandeMC/Kingdom-Hearts-Launchers#7]
Used this launcher quite a bit throughout my playthroughs but recently Windows is making it real annoying due to it declaring it as a virus. 
Anyway to remove this as a false positive? 
I know you can disable App screening in the action center but it will always turn it back on. 
Any update or solution would be appreciated! 

![image](https://github.com/user-attachments/assets/9ee0913b-fbc5-4b19-8630-1984df0262cb)

**Comment by SandeMC** [comment]
you can add the folder as an exception but it's better if i find a way to recompile it without malware detection or report it as a false positive so give me some time

**Comment by SandeMC** [comment]
@thevelcrosasquatch re-uploaded the latest package, see if the problem is still there

**Comment by thevelcrosasquatch** [comment]
> @thevelcrosasquatch re-uploaded the latest package, see if the problem is still there

It downloads and the zip file is not instantly deleted.
but Windows still flags it as a virus and doesn't allow it.
I appreciate anything you do and am also trying to report it as a false positive

**Comment by SandeMC** [comment]
i dont have it report on my end and virustotal doesn't mention microsoft, so i can't report it myself

**Comment by SandeMC** [comment]
reported it as a false positive to malwarebytes and microsoft idc about the rest

**Comment by thevelcrosasquatch** [comment]
thanks

**Comment by mer2329** [comment]
1.4 has false positive issues across many engines https://www.virustotal.com/gui/file/2e670db6722e4f9b1fa984b72f9386d20207d3843af70f5b1a13c6affb6ed49a/summary
