### ISSUE TITLE
launcher 1.4 wont open KH 0.2 BBS a fragmentory passage

### ISSUE THREAD

**Issue by mer2329** [SandeMC/Kingdom-Hearts-Launchers#9]
when i try and launch 0.2 bbs with this launcher nothing happens.

i tried making a shortcut of the executable next to the others, also tried a symlink. would try a hard link but i highly doubt that would work without me hardlinking all the nearby files as well.
i have a feeling the launcher isnt opening the execuable. maybe because its not in the main folder
the execuables for DDD and 2.8 is in "[SteamLibrary]\steamapps\common\KINGDOM HEARTS HD 2.8 Final Chapter Prologue"
0.2 BBS however is deeper in there specificly "[SteamLibrary]\steamapps\common\KINGDOM HEARTS HD 2.8 Final Chapter Prologue\KINGDOM HEARTS 0.2 Birth by Sleep\Binaries\Win64"

**Comment by SandeMC** [comment]
Does some error show up? Cuz I do point to that directory, if no error shows up then it should launch per usual
https://github.com/SandeMC/Kingdom-Hearts-Launchers/blob/master/Kingdom%20Hearts%202%20Launcher/MainWindow.xaml.cs#L172C1-L175C14

**Comment by mer2329** [comment]
nope no error. even verified my game installation

**Comment by mer2329** [comment]
the launcher just closes

**Comment by SandeMC** [comment]
if no error pops up it means it does find and run the exe, but it crashes for some reason
i don't have 2.8 installed to test sadly

**Comment by mer2329** [comment]
i was direct launching it. thats why. it works if launched through steam
